CREATE OR REPLACE PACKAGE KISISEL_NOT_TAKIBI AS
    FUNCTION GONULLU_STAJ_TURU_SAYISI(OGR_ID PLS_INTEGER)
    RETURN PLS_INTEGER;
    FUNCTION ZORUNLU_STAJ_TURU_SAYISI(OGR_ID PLS_INTEGER)
    RETURN PLS_INTEGER;
    FUNCTION DEVAMLILIK_ORANI(OGR_ID PLS_INTEGER)
    RETURN VARCHAR2;
    FUNCTION MAILLER(OGR_ID PLS_INTEGER)
    RETURN VARCHAR2;
END KISISEL_NOT_TAKIBI;
/



CREATE OR REPLACE PACKAGE BODY KISISEL_NOT_TAKIBI IS
    FUNCTION GONULLU_STAJ_TURU_SAYISI(OGR_ID PLS_INTEGER) RETURN PLS_INTEGER IS
        GONULLU_STAJ PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO GONULLU_STAJ FROM A_STAJLAR S
        JOIN 
            A_OGRENCI O ON S.OGRENCI_ID = O.OGRENCI_NUMARASI
            WHERE OGRENCI_ID = OGR_ID
            AND STAJ_TURU = 'Gönüllü'
        GROUP BY STAJ_TURU;
    RETURN GONULLU_STAJ;
    END; 
      FUNCTION ZORUNLU_STAJ_TURU_SAYISI(OGR_ID PLS_INTEGER) RETURN PLS_INTEGER IS
        ZORUNLU_STAJ PLS_INTEGER;
    BEGIN
        SELECT COUNT(*) INTO ZORUNLU_STAJ FROM A_STAJLAR S
        JOIN 
            A_OGRENCI O ON S.OGRENCI_ID = O.OGRENCI_NUMARASI
            WHERE OGRENCI_ID = OGR_ID
            AND STAJ_TURU = 'Zorunlu'
        GROUP BY STAJ_TURU;
    RETURN ZORUNLU_STAJ;
    END; 
    
    
    
    FUNCTION DEVAMLILIK_ORANI(OGR_ID PLS_INTEGER)RETURN VARCHAR2 IS
    DEVAM_ORANI VARCHAR2(100);
    BEGIN
        --RETURN(KATILIM_SAÐLANAN_DERS_SAYISI*TOPLAM_DERS_SAYISI)/100;
        SELECT 
           CASE
                WHEN MIN(DEVAM_ORANI)<50 THEN  CONCAT(A_DERS.DERS_ADI, ' DERSÝNDEN DEVAMSIZLIKTAN KALDI')
                ELSE CONCAT(A_DERS.DERS_ADI, ' DERSÝNDEN DEVAMSIZLIKTAN KALMADI')
            END DURUM INTO DEVAM_ORANI
        FROM A_DEVAMSIZLIK D
        JOIN 
            A_OGRENCI O ON D.OGRENCI_ID = O.OGRENCI_NUMARASI
        JOIN 
            A_DERS ON D.DERS_ID = A_DERS.DERSKODU
        WHERE OGRENCI_ID = OGR_ID
        GROUP BY DERS_ADI;
        RETURN DEVAM_ORANI;
    END;
    
    
    
    
        FUNCTION MAILLER(OGR_ID PLS_INTEGER) RETURN VARCHAR2 IS
    v_mail VARCHAR2(100);
    BEGIN
        SELECT 
            MAIL_ADRESI INTO v_mail
        FROM A_MAILLER M
        JOIN 
            A_OGRENCI O ON M.OGRENCI_ID = O.OGRENCI_NUMARASI
        WHERE OGRENCI_NUMARASI = OGR_ID;
        RETURN v_mail;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
        WHEN TOO_MANY_ROWS THEN
            RETURN NULL;
    END;
END KISISEL_NOT_TAKIBI;
/
    
    
    
    
    
    
declare
    ZORUNLU_STAJ_SAYISI  PLS_INTEGER;
    MAIL VARCHAR2(100);
    GONULLU_STAJ_SAYISI PLS_INTEGER;
    ORAN VARCHAR2(100);
begin 
    GONULLU_STAJ_SAYISI:=KISISEL_NOT_TAKIBI.GONULLU_STAJ_TURU_SAYISI(1821221018);
    MAIL:=KISISEL_NOT_TAKIBI.MAILLER(1821221021);
    ORAN:=KISISEL_NOT_TAKIBI.DEVAMLILIK_ORANI(1821221020);
    ZORUNLU_STAJ_SAYISI:=KISISEL_NOT_TAKIBI.ZORUNLU_STAJ_TURU_SAYISI(1821221018);
    
    
      dbms_output.put_line('Gönüllü Staj Sayýsý: '||GONULLU_STAJ_SAYISI);
      dbms_output.put_line('MAIL: '||MAIL);
      dbms_output.put_line('Devamsýzlýk oraný: '||ORAN);
      dbms_output.put_line('Zorunlu Staj Sasyýsý: '||ZORUNLU_STAJ_SAYISI);
end;


DECLARE
  CURSOR c_satir
  IS
    SELECT 
           OGRENCI_NUMARASI,DERS_ADI,DERS_GUNU
        FROM A_DERS D
        JOIN 
            A_DERSPROGRAMLARI DP ON D.DERSKODU = DP.DERS_ID
        JOIN 
            A_OGRENCI O ON DP.OGRENCI_ID = O.OGRENCI_NUMARASI
        WHERE OGRENCI_NUMARASI = 1821221018
        group by OGRENCI_NUMARASI,DERS_ADI,DERS_GUNU
        order by ders_gunu;
begin 
for x in c_satir
 loop
         dbms_output.put_line( x.OGRENCI_NUMARASI || ' Numaralý öðrenci ' ||  x.DERS_GUNU || ' gününde ' || x.DERS_ADI || ' adlý dersi vardýr. ');
        end loop;
    end;
    









CREATE OR REPLACE TRIGGER SilinenSýnavlar
BEFORE INSERT OR UPDATE 
   ON A_SINAVTAKVIMI
   REFERENCING OLD AS old NEW AS new
   FOR EACH ROW
BEGIN
        INSERT INTO A_SILINENSINAVTARIHLERI
   ( ID,
     OGRENCI_ID,
     DERS_ID,
     SINAV_TARIHI,
     SINAV_YERI)
   VALUES
   ( :new.ID,
     :new.OGRENCI_ID,
     :new.DERS_ID,
     :new.SINAV_TARIHI,
     :new.SINAV_YERI);
END;
/

SELECT * FROM A_SILINENSINAVTARIHLERI

SELECT * FROM A_SINAVTAKVIMI


DROP TABLE A_SINAVTAKVIMI



    
    
    